name: MommonsLoader
main: cz.maku.mommons.plugin.MommonsPlugin
author: itIsMaku
description: Plugin what loads every plugin depends on Mommons
version: 2.0.1
softdepend:
  - HolographicDisplays
api-version: 1.17